name: Restart test env

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
    - name: Restart service
      uses: Myjetwallet/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA__ST_TEST }}
        NAMESPACE: marketing-box
        POD: marketing-box-registration-service
